In [2]:
import pandas as pd
import csv

def process_cbp_metadata(file_path):
    cbp_dict = {}
    with open(file_path, 'r', newline='', encoding='utf-8') as csvfile:
        csv_reader = csv.reader(csvfile)
        next(csv_reader, None)
        for row in csv_reader:
            if len(row) == 2:
                cbp_dict[row[0]] = row[1]
    return cbp_dict

def process_year_data(year, secondary_year):
    file_path = f'CBP{year}.CB{secondary_year}00CBP-Data.csv'
    meta_data_file_path = 'CBP2018.CB1800CBP-Column-Metadata.csv'

    df = pd.read_csv(file_path)
    cbp_dict = process_cbp_metadata(meta_data_file_path)

    df = df.rename(columns=cbp_dict)

    # filtered_columns = [
    #     col for col in df.columns
    #     if "Establishments" in col or "Geography" in col or "Geographic Area Name" in col
    # ]

    # df = df[filtered_columns]
    df = df.iloc[1:]  # Remove the first row if it contains column descriptions

    # Add a year column
    # df['Year'] = year

    return df

# Process data for years 2018 to 2022
years = range(2018, 2023)
secondary_years = range(18, 23)
zipped_years = dict(zip(years, secondary_years))
dfs = []

for year, secondary_year in zipped_years.items():
    try:
        df = process_year_data(year, secondary_year)
        dfs.append(df)
        print(f"Successfully processed data for {year}")
    except FileNotFoundError:
        print(f"File for year {year} not found. Skipping.")
    except Exception as e:
        print(f"Error processing data for {year}: {str(e)}")

# Combine all dataframes
combined_df = pd.concat(dfs, ignore_index=True)

# Display the first few rows of the combined dataframe
print("\nFirst few rows of the combined dataframe:")
display(combined_df.head())

# Print some information about the combined dataset
# print(f"\nTotal number of rows: {len(combined_df)}")
# print(f"Years included: {combined_df['Year'].unique()}")
# print(f"\nColumns in the dataset:")
# for col in combined_df.columns:
#     print(col)

# combined_df.to_csv('combined_cbp_data_2018_2022.csv', index=False)

<ipython-input-2-2ac54c97d855>:18: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Successfully processed data for 2018

<ipython-input-2-2ac54c97d855>:18: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Successfully processed data for 2019

<ipython-input-2-2ac54c97d855>:18: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Successfully processed data for 2020

<ipython-input-2-2ac54c97d855>:18: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Successfully processed data for 2021

<ipython-input-2-2ac54c97d855>:18: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Successfully processed data for 2022

First few rows of the combined dataframe:

,Geographic identifier code,Geographic Area Name,2017 NAICS code,Meaning of NAICS code,Legal form of organization code,Meaning of Legal form of organization code,Employment size of establishments code,Meaning of Employment size of establishments code,Year,Number of establishments,"Annual payroll ($1,000)",Noise range for annual payroll,"First-quarter payroll ($1,000)",Noise range for first-quarter payroll,Number of employees,Noise range for number of employees,Unnamed: 16
0,0500000US01001,"Autauga County, Alabama",00,Total for all sectors,001,All establishments,001,All establishments,2018,855,373865,G,90886,G,11397,G,NaN
1,0500000US01001,"Autauga County, Alabama",00,Total for all sectors,001,All establishments,210,Establishments with less than 5 employees,2018,398,N,N,N,N,N,N,NaN
2,0500000US01001,"Autauga County, Alabama",00,Total for all sectors,001,All establishments,220,Establishments with 5 to 9 employees,2018,200,N,N,N,N,N,N,NaN
3,0500000US01001,"Autauga County, Alabama",00,Total for all sectors,001,All establishments,230,Establishments with 10 to 19 employees,2018,115,N,N,N,N,N,N,NaN
4,0500000US01001,"Autauga County, Alabama",00,Total for all sectors,001,All establishments,241,Establishments with 20 to 49 employees,2018,91,N,N,N,N,N,N,NaN

In [3]:
combined_df = combined_df.loc[:, ~combined_df.columns.str.contains('Noise', case=False)]

In [5]:
combined_df.shape

(1127278, 14)